### ISSUE TITLE
Smart Mirror hangs until I ctrl-c out of it and I get a python error.

### ISSUE THREAD

**Issue by NyleCohen** [HackerHouseYT/Smart-Mirror#111]
Hi! I just installed the Smart Mirror but when I run it it hangs until I Control-C out of it and then I get a python error.

The error:
```

^CTraceback (most recent call last):
  File "smartmirror.py", line 329, in <module>
    w = FullscreenWindow()
  File "smartmirror.py", line 309, in __init__
    self.weather = Weather(self.topFrame)
  File "smartmirror.py", line 123, in __init__
    self.get_weather()
  File "smartmirror.py", line 140, in get_weather
    location_req_url = "http://freegeoip.net/json/%s" % self.get_ip()
  File "smartmirror.py", line 128, in get_ip
    req = requests.get(ip_url)
  File "/home/pi/.local/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/pi/.local/lib/python2.7/site-packages/requests/sessions.py", line 247, in resolve_redirects
    **adapter_kwargs
  File "/home/pi/.local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/pi/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/pi/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/pi/.local/lib/python2.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/pi/.local/lib/python2.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/pi/.local/lib/python2.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt
```

**Comment by Jeromy23c** [comment]
Show your Script but take out any imformation you dont want to show
