### ISSUE TITLE
Currently PLEASE HELP MEE

### ISSUE THREAD

**Issue by nfao2** [HackerHouseYT/Smart-Mirror#119]
hi I keep getting this error upon starting up.
raceback (most recent call last):
  File "guitest.py", line 164, in get_weather
    temperature2 = "%s%s" % (str(int(weather_obj['currently']['temperature'])), degree_sign)
KeyError: 'currently'
Error: 'currently'. Cannot get weather.
Traceback (most recent call last):
  File "guitest.py", line 239, in get_headlines
    headline = NewsHeadline(self.headlinesContainer, post.title)
  File "guitest.py", line 252, in __init__
    image = Image.open("assets/Newspaper.png")
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'assets/Newspaper.png'
Error: [Errno 2] No such file or directory: 'assets/Newspaper.png'. Cannot get news.

please please help

**Comment by harishMadhavan1010** [comment]
1. Did you pip install the requirements properly and set up API for darksky? 
2. Did you download all the assets properly and kept them within the python project folder?
