### ISSUE TITLE
Having Issues with the weather. What am I doing wrong?

### ISSUE THREAD

**Issue by wood-dj** [HackerHouseYT/Smart-Mirror#17]
I have 0 knowledge in this. When I copy all the info i get this line of error code. Anyone know what I am doing wrong? 
Traceback (most recent call last):
  File "smartmirror.py", line 145, in get_weather
    weather_obj = json.loads(r.text)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Error: No JSON object could be decoded. Cannot get weather.

**Comment by baett** [comment]
How did you fix this?
