### ISSUE TITLE
Cannot get weather 

### ISSUE THREAD

**Issue by jamesbetterman** [HackerHouseYT/Smart-Mirror#47]
this is my problem
Traceback (most recent call last):
  File "smartmirror.py", line 158, in get_weather
    weather_obj = json.loads(r.text)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Error: No JSON object could be decoded. Cannot get weather.

**Comment by J1306** [comment]
Make sure you've deleted the < > Parenthesis when inputing the api token, It then worked for me.

**Comment by mauri9421** [comment]
I have the same problem!
![2017-02-05-232310_1366x768_scrot](https://cloud.githubusercontent.com/assets/25572486/22634730/17cfa9f4-ebfb-11e6-906f-cbc19c3f2522.png)
![2017-02-06-024756_1366x768_scrot](https://cloud.githubusercontent.com/assets/25572486/22634731/17d39b40-ebfb-11e6-931b-61934670e504.png)
Help please.

**Comment by dhikanime** [comment]
i have the same problem, & i already remove <>. anyone help pls :<

Traceback (most recent call last):
  File "smartmirror.py", line 157, in get_weather
    weather_obj = json.loads(r.text)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Error: No JSON object could be decoded. Cannot get weather.

**Comment by mauri9421** [comment]
Probably is the api... Change it for this!
![api](https://cloud.githubusercontent.com/assets/25572486/23220499/387dd958-f8f0-11e6-8a59-a38b71da4df3.JPG)
Good luck!

**Comment by dhikanime** [comment]
pardon me i've already change like that before. but that make new problem :<

Traceback (most recent call last):
  File "smartmirror.py", line 160, in get_weather
    temperature2 = "%s%s" % (str(int(weather_obj['currently']['temperature'])), degree_sign)
KeyError: 'currently'
Error: 'currently'. Cannot get weather.

here's my code btw, am i did something wrong? :(


![2017-02-23-010643_1024x768_scrot](https://cloud.githubusercontent.com/assets/15216696/23225574/e719eb90-f964-11e6-98d1-7f27f6bad874.png)
![2017-02-23-010801_1024x768_scrot](https://cloud.githubusercontent.com/assets/15216696/23225577/e7292db2-f964-11e6-951d-9a0d9eb5782d.png)
![2017-02-23-010820_1024x768_scrot](https://cloud.githubusercontent.com/assets/15216696/23225575/e72587de-f964-11e6-8dc6-2b318657ad14.png)
![2017-02-23-010833_1024x768_scrot](https://cloud.githubusercontent.com/assets/15216696/23225576/e7288b3c-f964-11e6-8861-8ec47cf233c1.png)
![2017-02-23-010847_1024x768_scrot](https://cloud.githubusercontent.com/assets/15216696/23225578/e72a9936-f964-11e6-9103-fe702f3cd882.png)
![2017-02-23-010902_1024x768_scrot](https://cloud.githubusercontent.com/assets/15216696/23225579/e72af3a4-f964-11e6-9368-c779c2f32f91.png)

**Comment by dmrowe84** [comment]
I'm seeing a lot of people with this issue, even in the closed section. 
i myself am having this issue, after browsing multiple forums i cannot for the life of me figure this out. can someone please solve this (im sure its stupidly simple) issue.
here's a screen shot of my .py file
![2017-03-09-221036_1920x1080_scrot](https://cloud.githubusercontent.com/assets/26317586/23781921/1ccbee16-0516-11e7-9df6-215d0cffc361.png)

**Comment by dmrowe84** [comment]
oh and heres the error message 
![2017-03-09-221904_1920x1080_scrot](https://cloud.githubusercontent.com/assets/26317586/23781996/9beb8c92-0516-11e7-8032-11ec4ab7c585.png)

**Comment by dmrowe84** [comment]
@mauri9421 
Did you find a solution to the error message?

**Comment by JanArneBosnes** [comment]
@dmrowe84
You have not set the ui_locale to anything. Its on line 20 and before time_format.
You can check your ui by typing this in the terminal:
locale -a

I got 'en_GB.utf8'

**Comment by PabloPi1** [comment]
@JanArneBosnes I tried that and still nothing, the same message error pops up
