### ISSUE TITLE
getting error when running python smartmirror.py

### ISSUE THREAD

**Issue by blondespot11** [HackerHouseYT/Smart-Mirror#55]
pi@raspberrypi:/Code/Smart-Mirror/assets $ python smartmirror.py
Traceback (most recent call last):
  File "smartmirror.py", line 173, in get_weather
    image = Image.open(icon2)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2251, in open
    fp = builtins.open(fp, "rb")
IOError: [Errno 2] No such file or directory: 'assets/Cloud.png'
Error: [Errno 2] No such file or directory: 'assets/Cloud.png'. Cannot get weather.
Traceback (most recent call last):
  File "smartmirror.py", line 235, in get_headlines
    headline = NewsHeadline(self.headlinesContainer, post.title)
  File "smartmirror.py", line 248, in __init__
    image = Image.open("assets/Newspaper.png")
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2251, in open
    fp = builtins.open(fp, "rb")
IOError: [Errno 2] No such file or directory: 'assets/Newspaper.png'
Error: [Errno 2] No such file or directory: 'assets/Newspaper.png'. Cannot get news.

I HAVE CONFIRMED THOSE FILES ARE LOCATED IN assets directory
pi@raspberrypi:/Code/Smart-Mirror/assets $ ls -l
total 1116
-rwxr--r-- 1 pi pi  54893 Feb 12 16:08 Cloud.png
-rwxr--r-- 1 pi pi     56 Feb 12 16:08 CREDITS.txt
-rwxr--r-- 1 pi pi  71281 Feb 12 16:08 Hail.png
-rwxr-xr-x 1 pi pi  86360 Feb 12 16:08 Haze.png
-rwxr--r-- 1 pi pi   1070 Feb 12 16:08 LICENSE
-rwxr--r-- 1 pi pi   4358 Feb 12 16:08 LICENSE.txt
-rwxr--r-- 1 pi pi  73119 Feb 12 16:08 Moon.png
-rwxr--r-- 1 pi pi 120601 Feb 12 16:08 Newspaper.png
-rwxr--r-- 1 pi pi  71512 Feb 12 16:08 PartlyMoon.png
-rwxr--r-- 1 pi pi  75943 Feb 12 16:08 PartlySunny.png
-rwxr--r-- 1 pi pi  66161 Feb 12 16:08 Rain.png
-rw-r--r-- 1 pi pi   1190 Feb 12 16:08 README.md
-rwxr--r-- 1 pi pi     27 Feb 12 16:08 requirements.txt
-rwxr--r-- 1 pi pi    971 Feb 12 16:08 setup.py
-rwxr--r-- 1 pi pi  13017 Mar 14 11:18 smartmirror.py
-rwxr--r-- 1 pi pi  88925 Feb 12 16:08 Snow.png
-rwxr--r-- 1 pi pi  73883 Feb 12 16:08 Storm.png
-rw-r--r-- 1 pi pi  91276 Feb 12 16:08 Sun.png
-rw-r--r-- 1 pi pi  60635 Feb 12 16:08 Sunrise.png
-rw-r--r-- 1 pi pi  91868 Feb 12 16:08 Tornado.png
-rw-r--r-- 1 pi pi  40098 Feb 12 16:08 Wind.png

Not sure what i did wrong.  I'm so close.  Any advice or help would be greatly appreciated

**Comment by blondespot11** [comment]
Nevermind.  i think i fixed it.  had smartmirror.py in wrong directory
