### ISSUE TITLE
Can´t run bot.py

### ISSUE THREAD

**Issue by kiiRRa** [HackerHouseYT/Smart-Mirror#66]
I get this errors while tying to run ¨python bot.py¨ : 
Warning: OpenCV not installed. To use facial recognition, make sure you've properly configured OpenCV.
Found face
Traceback (most recent call last):
  File "bot.py", line 254, in <module>
    bot.start()
  File "bot.py", line 43, in start
    recognizer, audio = self.speech.listen_for_audio()
  File "/home/pi/MagicMirror/modules/AI-Smart-Mirror-master/speech.py", line 32, in listen_for_audio
    m = sr.Microphone()
  File "/home/pi/MagicMirror/modules/AI-Smart-Mirror-master/hhsmartmirror/local/lib/python2.7/site-packages/speech_recognition/__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/home/pi/MagicMirror/modules/AI-Smart-Mirror-master/hhsmartmirror/local/lib/python2.7/site-packages/speech_recognition/__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation

**Comment by safaaelbrans** [comment]
can you help me please i need the source code The Smart Mirror lets me book an Uber, check emails, Facebook & Twitter
