### ISSUE TITLE
Weather is not working

### ISSUE THREAD

**Issue by elyasnaji** [HackerHouseYT/Smart-Mirror#90]
i have already put in the token. The app launches after this code and displays time, news but not weather

`Traceback (most recent call last):
  File "smartmirror.py", line 157, in get_weather
    weather_obj = json.loads(r.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Error: No JSON object could be decoded. Cannot get weather.
pi@raspberrypi:~/Smart-Mirror $ 
`

**Comment by delahoya1** [comment]
make sure you delete the <>

**Comment by delahoya1** [comment]
around the token

**Comment by rdyer550** [comment]
my weather will not display! final project is due soon please help!
File "smartmirror.py", line 160, in get_weather
              temperature2 = "%s%s" % (str(int(weather_obj['currently']['temperature'])), degree_sign)
KeyError: 'currently' 
Error : 'currently' .  Cannot get weather.
