### ISSUE TITLE
Import request modules

### ISSUE THREAD

**Issue by analexius** [HackerHouseYT/Smart-Mirror#98]
Hi guys,
everything went smoothly, but i get this when i start up:

File "smartmirror.py", line 9, in <module>
    import requests
ImportError: No module named requests

Any idea what i missed?

rgds,
Axs

**Comment by nickever** [comment]
You need to install the requests package from PiPy. In terminal try:
$sudo pup install requests

**Comment by analexius** [comment]
Will try tonight, thanks a mill
Axs

**Comment by analexius** [comment]
(cv) pi@GrosPi:~ $ sudo pip install requests
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages
(cv) pi@GrosPi:~/Smart-Mirror $ python smartmirror.py 
Traceback (most recent call last):
  File "smartmirror.py", line 9, in <module>
    import requests
ImportError: No module named requests

**Comment by nickever** [comment]
Check it’s installed for python 3 as well. 

$ pip3 freeze
(This will show a list of installed packages)

If not installed for python 3, then;
$ sudo pip3 install requests

Good luck

**Comment by bervin61** [comment]
On the same lines as nickever, you can check what version of python you are running by (from the python shell)
`import sys
sys.version`
if it's installed for your version, we need to troubleshoot.
